### ISSUE TITLE
Getting Response for preflight has invalid HTTP status code 401

### ISSUE THREAD

**Issue by chamanklalwani** [isopropylcyanide/Jwt-Spring-Security-JPA#1]
Hi,

For /api/user/admins URI, I am getting **Response for preflight has invalid HTTP status code 401** error.

**Comment by isopropylcyanide** [comment]
Are you passing the correct JWT token in the Authorization header? 
Can you please share the exact postman request payload to reproduce this issue?

**Comment by chamanklalwani** [comment]
Hi Aman,

Yes, I am passing the correct JWT token in the Authorization header.

Actually, I have an angular App which accesses the backend (Spring Boot application),  Initially, I was getting CORS error. So I added CORS filter and after the CORS filter, I was getting "preflight has an invalid HTTP status code 401". For this, I needed to modify **WebSecurityConfig.java** file. I allowed **HTTP.OPTIONS** to the following 2 methods. 

1) public void configure(WebSecurity web) throws Exception

web.ignoring().antMatchers("/v2/api-docs", "/configuration/ui", "/swagger-resources/**", "/configuration/**", "/swagger-ui.html", "/webjars/**").**antMatchers(HttpMethod.OPTIONS, "/**")**;

2) protected void configure(HttpSecurity http) throws Exception {

.antMatchers("/**/api/auth/**").permitAll()
**.antMatchers(HttpMethod.OPTIONS, "**").permitAll()**   //allow CORS option calls
.anyRequest().authenticated();

After doing the above changes. Its working fine now.

Thanks

**Comment by isopropylcyanide** [comment]
Thanks for sharing. Marking the issue as closed.
