### ISSUE TITLE
Does the constructor in DeviceInfo.java correct?

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#15]
in file [DeviceInfo.java](https://github.com/isopropylcyanide/Jwt-Spring-Security-JPA/blob/master/src/main/java/com/accolite/pru/health/AuthApp/model/payload/DeviceInfo.java) on line 41 there is a constructor like this:

```
public DeviceInfo(String deviceId, DeviceType deviceTypem, String notificationToken) {
        this.deviceId = deviceId;
        deviceType = deviceType;
        notificationToken = notificationToken;
    }
```

I think it must changed like this:
```
public DeviceInfo(String deviceId, DeviceType deviceType, String notificationToken) {
        this.deviceId = deviceId;
        this.deviceType = deviceType;
        this.notificationToken = notificationToken;
    }
```

Am I right?

**Comment by isopropylcyanide** [comment]
You are correct to point it out. The instance members are not being set (`this.`) to be explicit. 

```java
this.deviceId = deviceId;
this. notificationToken = notificationToken;
```

Can you raise a PR for this and any other inconsistencies you come across? Will be happy to review.

**Comment by mjza** [comment]
Sure I will try

**Comment by mjza** [comment]
I made the pull request. By the way, it was the first time I made a PR 👯

**Comment by isopropylcyanide** [comment]
Thank you for your efforts. You're a contributor now. Good job 👍

**Comment by mjza** [comment]
Thanks. I will close the issue.
