### ISSUE TITLE
I got error

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#16]
I tried to used your code in new spring-boot project but I got the following error:

> In attribute 'userList', the "mapped by" value 'roles' cannot be resolved to an attribute on the target entity.

Any suggestion for solving that? Everything is copy past except the spring boot version that I use the latest, but it is interesting that it shows this error for the following line of code in Role.java:

```
 @ManyToMany(mappedBy = "roles", fetch = FetchType.LAZY)
    @JsonIgnore
    private Set<User> userList = new HashSet<>();
```

> failed to lazily initialize a collection of role: me.odata.model.Role.userList, could not initialize prox
y - no Session

**Comment by mjza** [comment]
However when I upgrade the spring boot version to `2.3.0.RELEASE` it has problem with `javax.validation` also.

**Comment by mjza** [comment]
It is needed to add the following line to application.properties:

```
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
```

**Comment by isopropylcyanide** [comment]
Thanks for sharing. It is possible that few dependencies are decoupled in the newer versions of Spring boot which were not in the version used in this project.
