### ISSUE TITLE
Why do you use java.time.Instant?

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#18]
I would suggest to use `java.util.Date` instead of `java.time.Instant` in `DateAudit.java` because some libraries like Olingo JPA does not support `java.time.Instant`

**Comment by isopropylcyanide** [comment]
I think this [article](https://programminghints.com/2017/05/still-using-java-util-date-dont/) should sum up why `java.util.date` is deprecated. 

As for the compatibility with Olingo API, I'm not sure why it would not be compatible? A `java.time.Instant` can be converted to a `java.util.date`

**Comment by mjza** [comment]
I tried to use a converter even but it was not run automatically as claimed in this tutorial:

https://www.adam-bien.com/roller/abien/entry/new_java_8_date_and

At the moment I have no clew why the JPA does not support `java.time.Instant`, hence I have changed the manually to `java.util.date`.

**Comment by mjza** [comment]
Article about JPA does not support Instant:

https://github.com/eclipse-ee4j/jpa-api/issues/63

https://stackoverflow.com/questions/49309076/why-jpa-does-not-support-java-time-instant
