### ISSUE TITLE
Error object does not have same structure for all erros!

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#25]
The error response that returns by the back-end does not have a common attributes and structure!
Some sample cases that I see:
1. When both user and pass are wrong!
```
{
cause: "org.springframework.security.authentication.BadCredentialsException",
data: "Bad credentials",
success: false,
timestamp: "2020-07-15T14:21:20.563Z"
}
```
2. When user is not yet activated
```
{
error: "Unauthorized",
message: "",
path: "/api/auth/login",
status: 401,
timestamp: "2020-07-15T14:24:05.201+00:00"
}
```

**Comment by isopropylcyanide** [comment]
You can write a custom exception mapper for this use case. A common structure would be good to have in the codebase.

**Comment by isopropylcyanide** [comment]
Not an issue.
