### ISSUE TITLE
Password reset issue

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#28]
How do we generate token for password reset?

Is `api\auth\password\reset` for a logged in user? 

Or is it for resetting a forgotten password?

If this is the second case how do we request for a new email with reset token? Because I saw you used a token in the payload!

**Comment by mjza** [comment]
if this is for a logged in user don't you think it is better we put it under `api\user` end point?

**Comment by isopropylcyanide** [comment]
**api/auth/password/resetlink**  and **/api/auth/password/reset**  are for a logged out user.
You cannot request a new email as of now. The password will be delivered to your original mail.

**Comment by mjza** [comment]
Please check this picture:

![reset](https://user-images.githubusercontent.com/12872673/45047624-3628e480-b097-11e8-944f-c88b1cd0c231.png)

What is that token in the body?
How does the back-end know which user requested for resetting the pass?

**Comment by isopropylcyanide** [comment]
The token is a password reset token (PRT) mapped in the **password_reset_token** against your email Id. This is not a JWT token used for authentication. 
The PRT should be sent to your email address. The code base is hooked up with java mail clients. You should specify your sender password and email to be able to receive an email on the account which has forgotten your password.
