### ISSUE TITLE
Swagger shows redundant data for user apis

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#30]
When we visit [http://localhost:9004/swagger-ui.html#/user-controller/updateUserPasswordUsingPOST](http://localhost:9004/swagger-ui.html#/user-controller/updateUserPasswordUsingPOST) we will see lots of redundant data which is generated automatically from `User` model. How can we get read of them?

> accountNonExpired
> boolean
> (query)	
> accountNonLocked
> boolean
> (query)	
> active
> boolean
> (query)	
> authorities[0].authority
> string
> (query)	
> createdAt
> string($date-time)
> (query)	
> credentialsNonExpired
> boolean
> (query)	
> email
> string
> (query)	
> emailVerified
> boolean
> (query)	
> enabled
> boolean
> (query)	
> firstName
> string
> (query)	
> id
> integer($int64)
> (query)	
> lastName
> string
> (query)	
> password
> string
> (query)	
> roles[0].adminRole
> boolean
> (query)	
> roles[0].id
> integer($int64)
> (query)	
> roles[0].role
> string
> (query)	
> Available values : ROLE_ADMIN, ROLE_USER
> 
> roles[0].userList[0].active
> boolean
> (query)	
> roles[0].userList[0].createdAt
> string($date-time)
> (query)	
> roles[0].userList[0].email
> string
> (query)	
> roles[0].userList[0].emailVerified
> boolean
> (query)	
> roles[0].userList[0].firstName
> string
> (query)	
> roles[0].userList[0].id
> integer($int64)
> (query)	
> roles[0].userList[0].lastName
> string
> (query)	
> roles[0].userList[0].password
> string
> (query)	
> roles[0].userList[0].updatedAt
> string($date-time)
> (query)	
> roles[0].userList[0].username
> string
> (query)	
> updatePasswordRequest
> (body)

**Comment by mjza** [comment]
It is easy we have to add `@ApiIgnore` to the `getUserProfile` function inside the `UserController`:

```
public ResponseEntity<String> getUserProfile(@ApiIgnore @CurrentUser CustomUserDetails currentUser) { ....
```

Don't forget to import it aswell:

```
import springfox.documentation.annotations.ApiIgnore;
```

**Comment by isopropylcyanide** [comment]
Right. There needs to be a way of selectively including what we want. By default it might scan for all models.

**Comment by mjza** [comment]
Shall I make a PR for this also?

**Comment by isopropylcyanide** [comment]
Yea, why not. I don't see any point in Swagger annotations for the models and DTOs

**Comment by isopropylcyanide** [comment]
@mjza Still willing to raise a PR here?

**Comment by mjza** [comment]
@isopropylcyanide No time sorry.

**Comment by isopropylcyanide** [comment]
@mjza Sure, thanks. Not an issue.

**Comment by krupalshah** [comment]
@isopropylcyanide Please merge this PR: https://github.com/isopropylcyanide/Jwt-Spring-Security-JPA/pull/42

**Comment by isopropylcyanide** [comment]
@krupalshah Thanks for pitching in.
