### ISSUE TITLE
WebSecurityConfigurerAdapter does not serve index.html when it's name does not mentioned in the URL explicitly

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#34]
Hi @isopropylcyanide: I know it is not 100% related to this project, but maybe you can give me some advice. Please check this 2 questions: [link1](https://stackoverflow.com/questions/63175074/websecurityconfigureradapter-does-not-serve-index-html-when-its-name-does-not-m), [link2](https://stackoverflow.com/questions/63188491/how-to-add-rewrite-rule-to-spring-boot-2-3-1)

**Comment by isopropylcyanide** [comment]
No idea man. We use Dropwizard at work and directly deal with URIs. We use the `seeOther` methods to achieve that. In the links you've shared someone has mentioned the `HttpServletResponse` method. I think that can be worth exploring.

**Comment by mjza** [comment]
I tried that, but does not have any effect. I am really surprised that why it works when I run it with maven and not working with tomcat.

**Comment by isopropylcyanide** [comment]
Maven is a build tool. Tomcat is a servlet container. These two are completely unrelated.

**Comment by mjza** [comment]
I know but `mvn spring-boot:run` will run the build code that must run at the end in tomcat! The problem is visiting the root address will cause to serve `/index.html` but at the end the `WebSecurityConfigurerAdapter` will block it! I can see that in the console:

> ********************************************************************
> **********        Security debugging is enabled.       *************
> **********    This may include sensitive information.  *************
> **********      Do not use in a production system!     *************
> ********************************************************************
> 
> 
> 18:36:42.921 [main] INFO  o.s.scheduling.concurrent.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
> 18:36:43.180 [main] INFO  o.s.b.a.web.servlet.WelcomePageHandlerMapping - Adding welcome page: ServletContext resource [/index.html]
> 18:36:44.401 [main] INFO  s.d.s.web.plugins.DocumentationPluginsBootstrapper - Context refreshed
> 18:36:44.687 [main] INFO  s.d.s.web.plugins.DocumentationPluginsBootstrapper - Found 2 custom documentation plugin(s)
> 18:36:45.106 [main] INFO  s.d.spring.web.scanners.ApiListingReferenceScanner - Scanning for api listing references
> 18:36:46.391 [main] INFO  s.d.spring.web.scanners.ApiListingReferenceScanner - Scanning for api listing references
> 18:36:46.489 [main] INFO  me.cimply.ask.odata.Application - Started Application in 50.292 seconds (JVM running for 73.85)
> 18:36:46.923 [main] INFO  org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8181"]
> 18:36:46.946 [main] INFO  org.apache.catalina.startup.Catalina - Server startup in [71,017] milliseconds
> 18:36:51.455 [http-nio-8181-exec-3] INFO  o.a.c.c.C.[.[.[/cimply-backend-olingo-odata2-jpa] - Initializing Spring DispatcherServlet 'dispatcherServlet'
> 18:36:51.457 [http-nio-8181-exec-3] INFO  org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
> 18:36:51.490 [http-nio-8181-exec-3] INFO  org.springframework.web.servlet.DispatcherServlet - Completed initialization in 33 ms
> 18:36:51.526 [http-nio-8181-exec-3] INFO  Spring Security Debugger - 
> 
> ************************************************************
> 
> Request received for GET '/index.html':
> 
> org.apache.catalina.connector.RequestFacade@1d28e57e
> 
> servletPath:/index.html
> pathInfo:null
> headers: 
> host: localhost:8181
> connection: keep-alive
> cache-control: max-age=0
> upgrade-insecure-requests: 1
> user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
> accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
> sec-fetch-site: none
> sec-fetch-mode: navigate
> sec-fetch-user: ?1
> sec-fetch-dest: document
> accept-encoding: gzip, deflate, br
> accept-language: en-US,en;q=0.9,de;q=0.8,fa;q=0.7
> 
> 
> Security filter chain: [
>   WebAsyncManagerIntegrationFilter
>   SecurityContextPersistenceFilter
>   HeaderWriterFilter
>   CorsFilter
>   LogoutFilter
>   JwtAuthenticationFilter
>   RequestCacheAwareFilter
>   SecurityContextHolderAwareRequestFilter
>   AnonymousAuthenticationFilter
>   SessionManagementFilter
>   ExceptionTranslationFilter
>   FilterSecurityInterceptor
> ]
> 
> 
> ************************************************************

**Comment by mjza** [comment]
@isopropylcyanide We can add the following controller to redirect `\` to `\index`:

```java

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;

@Controller
public class AppController {
	
	@GetMapping("/")
    public String index() {		
        return "redirect:index.html";
    }
}
```
