### ISSUE TITLE
Using claims directly from JWT token claim

### ISSUE THREAD

**Issue by abdurrehmansyeds** [isopropylcyanide/Jwt-Spring-Security-JPA#36]
In JwtAuthenticationFilter, for each request there is a DB call for userDeatils, why not add necessary claims in JWT while creating and then reuse it for Authentication instead of loading userDetails again from DB.
In my opinion the DB call for each request will destroy the whole purpose of Jwt being Stateless

**Comment by isopropylcyanide** [comment]
@abdurrehmansyeds Necessary claim is being added in `JwtTokenProvider` in the form of a subject. `UserDetails` can be extended in the future. Subject is meant to be finite. Storing IDs is a perfect use case within the token.

We can however, explore a way to store only the relevant information and avoid the look up.

**Comment by ILyaCyclone** [comment]
Absolutely agree with @abdurrehmansyeds . Making a DB call on each request while using JWT completely destroys its major purpose. And it would perform worse than classic server-side session authorization schema which only goes to DB once per login.

**Comment by isopropylcyanide** [comment]
@ILyaCyclone What do you propose, instead?

**Comment by abdurrehmansyeds** [comment]
@isopropylcyanide I know this is very old question, I just checked its still open so replying.
 you are making DB call to get user roles and create UserNamePasswordAuthenticationToken so why not add roles claim as comma separated string, then upon receiving request we can easily extract roles from jwt

**Comment by isopropylcyanide** [comment]
Sure, that can be done @abdurrehmansyeds  Feel free to raise a PR.

**Comment by isopropylcyanide** [comment]
DB lookup is not required to fetch claims anymore. Thanks @abdurrehmansyeds
Marking the issue as closed.
