### ISSUE TITLE
How to get current user?

### ISSUE THREAD

**Issue by mjza** [isopropylcyanide/Jwt-Spring-Security-JPA#39]
Is there any API that we could get the current user anywhere?

**Comment by isopropylcyanide** [comment]
Hi. Not sure what you mean by anywhere. You can create any API and pass the current user context.
Read about [AuthenticationPrincipal](https://www.baeldung.com/get-user-in-spring-security) here.

In the current codebase, there's a `@CurrentUser` annotation that we use to obtain the current user. It simply is a wrapper over the `AuthenticationPrincipal`. You can check the usage in `UserController#me` API

**Comment by mjza** [comment]
I found this way also:

```java
import org.springframework.security.core.context.SecurityContextHolder;

// Extract current user
private CustomUserDetails getCurrentUser() {
	Object principal = SecurityContextHolder.getContext().getAuthentication().getPrincipal();
	CustomUserDetails customUserDetails = null;
	if (principal instanceof CustomUserDetails) {
		customUserDetails = (CustomUserDetails) principal;
	}
	return customUserDetails;
}
```
