### ISSUE TITLE
problem login

### ISSUE THREAD

**Issue by kipierre** [isopropylcyanide/Jwt-Spring-Security-JPA#4]
after launching the project Jwt-Spring-Security-JPA:

_http://localhost:8080/api/auth/register
_{"email":"pierre.kitio@yahoo.fr","password":"134","registerAsAdmin":true}
_I receive a confirmation email and I valid
_but when I want to login myself  , my user-device table in my database is empty

http://localhost:8080/api/auth/login

{"email":"pierre.kitio@yahoo.fr","password":"1234"

}
i receive :{"data":"Device info cannot be null","success":false}

**Comment by isopropylcyanide** [comment]
In Application properties, set 

```spring.jpa.hibernate.ddl-auto=create``` instead of 
```spring.jpa.hibernate.ddl-auto=none```

**Comment by kipierre** [comment]
spring.jpa.hibernate.ddl-auto=create I changed in this
the same problem persists my table user_device remains empty
    Le samedi 23 mars 2019 à 16:37:10 UTC+1, Aman Garg <notifications@github.com> a écrit :  
 
 This message is eligible for Automatic Cleanup! (notifications@github.com) Add cleanup rule | More info
 
In Application properties, set

spring.jpa.hibernate.ddl-auto=create instead of
spring.jpa.hibernate.ddl-auto=none

**Comment by isopropylcyanide** [comment]
Well, I'm unsure as to what's happening here. Can you please take a pull from the master and try again.
I've set the default to "create" mode.

**Comment by isopropylcyanide** [comment]
Marking it as closed.
