### ISSUE TITLE
Moving to Maven Wrapper from local installation

### ISSUE THREAD

**Issue by mmafrar** [isopropylcyanide/Jwt-Spring-Security-JPA#44]
The Maven Wrapper is an excellent choice for users that don't want to install Maven at all. Instead of installing many versions of it in the operating system, we can just use the project-specific wrapper script.

Below files needs to be added to the project as part of moving:
- mvnw: it's an executable Unix shell script used in place of a fully installed Maven
- mvnw.cmd: it's the Batch version of the above script
- mvn: the hidden folder that holds the Maven Wrapper Java library and its properties file

The wrapper should work with different operating systems such as:
- Linux
- macOS
- Windows
- Solaris

After moving to Maven Wrapper OS specific commands needs to be executed instead of generic `mvn` command, hence the documentation needs to be updated with the commands for UNIX/Linux and Windows based operating systems.

@isopropylcyanide your thoughts on this? If needed I can work on this and submit a pull request.

**Comment by isopropylcyanide** [comment]
@mmafrar I agree. This would help streamline the environment for all platforms. Yes, we can work towards it.
