### ISSUE TITLE
Remember me functionality.

### ISSUE THREAD

**Issue by talentedandrew** [isopropylcyanide/Jwt-Spring-Security-JPA#51]
Hi, I do you intent to add a 'Remember me' functionality in this repo? `remember me` functionality provided by spring security is pretty straight forward, but how can one integrate it with the jwt.

**Comment by isopropylcyanide** [comment]
Hi. *Remember me* can be solved by using a `refresh token` which is stored on the client (app cache/site local store). When the app is opened, the client makes a call to obtain a new `JWT` by using the refresh token. Using this `JWT`, the client can communicate with the backend for all secured APIs until the `JWT` further expires at which point a call to `/refresh` is made again. This can be played until 

- The refresh token expires (typically, a month, though configurable)
- Client loses the refresh token (hard reset, app cache clear)

The API's are already available. You just need to orchestrate them using the client/middleware.

**Comment by talentedandrew** [comment]
IMO the better way is to pass the refresh token in the `Set-Cookie` Header just after the login with `httpOnly` and `secure` flags. In this way the client can send a get request (something like `/rememberme`) to the server, along with the refresh token in the cookie (which was set by the server) and the server can validate that cookie and auto login.
Using this approach the client doesn't need to handle any tokens in its storage. And since its stored in the cookie with `httpOnly` and `Secure` flag it can't be modified by the client.

**Comment by isopropylcyanide** [comment]
I agree. This seems better.
