### ISSUE TITLE
could you share the postman project?

### ISSUE THREAD

**Issue by eduyayo** [isopropylcyanide/Jwt-Spring-Security-JPA#54]
hi!
could you share the postman project?
maybe in test/resources or something...

**Comment by eduyayo** [comment]
drop it!. I've created my own..

**Comment by isopropylcyanide** [comment]
Sorry for the late reply. I've updated the README to make the APIs non static #55 
Postman collection can be seen here Postman collection dump available [here](https://gist.github.com/isopropylcyanide/a4e8556814dbf28dc3320be59785b807)
