### ISSUE TITLE
Response status 401 is access_token expired or permission is denied

### ISSUE THREAD

**Issue by aungtuntun** [isopropylcyanide/Jwt-Spring-Security-JPA#7]
Hi,

How to I know response status 401 is user access_token is expired or user can't access to Admin role permission? Please.
=> token expired
```
{"timestamp": "2019-06-10T07:38:50.301+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/api/user/me"
}

```
=> denied permission
```
{
    "timestamp": "2019-06-10T08:45:15.922+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/api/user/admins"
}
```

**Comment by isopropylcyanide** [comment]
Hi @aungtuntun. Good point. This is a feature ask. At present we'll not be able to do this because we have a single source of exception handling in Servlet Filter Chain configured at **JwtAuthenticationEntryPoint**

What I can do is attach a **HandlerExceptionResolver** at the AuthenticationEntryPoint. 
If I am able to draw up a throwable instance from the servlet request, I can route it to the existing Controller advice.

https://github.com/isopropylcyanide/Jwt-Spring-Security-JPA/pull/8

I have submitted a PR for this. Please review and test it thoroughly and let me know if it suffices your use case.

**Comment by isopropylcyanide** [comment]
Attaching some screenshots for the generated response

**Invalid JWT**
![Invalid JWT](https://user-images.githubusercontent.com/12872673/59225194-bca5c000-8bed-11e9-9099-26b770d5742a.png)

**Expired JWT**
![Expired JWT](https://user-images.githubusercontent.com/12872673/59225292-f2e33f80-8bed-11e9-93fe-ea2da89004f1.png)

Notice, that I'm throwing the same HTTP response code 406 (Not Acceptable) for both of your cases which seems to be the plausible solution. You can demarcate them based on data.

However, should you to wish to throw a dedicated response code for "Expired JWT", you should create a new Exception and the handler with the custom code. Doing this should be relatively straightforward,

**Comment by aungtuntun** [comment]
Hi,
Thanks for suggestion. I just used custom response for Access denied and UnAuthorized.
=> Admin Register,
![image](https://user-images.githubusercontent.com/28741748/59586716-901c0780-9109-11e9-95c9-10198a69130f.png)

=> Admin login

![image](https://user-images.githubusercontent.com/28741748/59586809-c2c60000-9109-11e9-8f53-bd9306d0ef60.png)

=> Admin called user list
![image](https://user-images.githubusercontent.com/28741748/59587075-716a4080-910a-11e9-9289-6f8ba25448ed.png)


=> Admin Token expired.
![image](https://user-images.githubusercontent.com/28741748/59586989-35cf7680-910a-11e9-9250-606dcc413424.png)

=> User register 

![image](https://user-images.githubusercontent.com/28741748/59587148-9b236780-910a-11e9-91f5-7fa7f0770047.png)

=> User login
![image](https://user-images.githubusercontent.com/28741748/59587216-c8701580-910a-11e9-8e3d-6ad9519c776c.png)


=> User called user list
![image](https://user-images.githubusercontent.com/28741748/59587266-e76ea780-910a-11e9-8102-788435dbffb2.png)

EntryPoint for Unauthorized,

```
@Component
public class AuthenticationEntryPoint implements org.springframework.security.web.AuthenticationEntryPoint {

	@Override
	public void commence(HttpServletRequest request, HttpServletResponse response,
			AuthenticationException authException) throws IOException, ServletException {
		ApiResponse apiResponse = new ApiResponse(401, "Unauthorized. Token is expired", false);
		OutputStream outputStream = response.getOutputStream();
		ObjectMapper mapper = new ObjectMapper();
		mapper.writeValue(outputStream, apiResponse);
		outputStream.flush();
	}

}

```

Access Denied for permission,

```
@Component
public class AccessDeniedHandler implements org.springframework.security.web.access.AccessDeniedHandler {

	@Override
	public void handle(HttpServletRequest request, HttpServletResponse response,
			AccessDeniedException accessDeniedException) throws IOException, ServletException {
		
		ApiResponse apiResponse = new ApiResponse(403, "Access Denied", false);
		OutputStream outputStream = response.getOutputStream();
		ObjectMapper mapper = new ObjectMapper();
		mapper.writeValue(outputStream, apiResponse);
		outputStream.flush();
		
	}

}

```

ApiResponse.java

```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ApiResponse {

	private  int status;
	private  boolean success;
	private  String message;
	private  String timestamp;
	private  Object result;
	
	public ApiResponse(int status, String message, boolean success) {
		this.status = status;
		this.message = message;
		this.success = success;
		this.timestamp = Instant.now().toString();
	}
		
}

```
Thanks for help.
