### ISSUE TITLE
500 Internal server

### ISSUE THREAD

**Issue by im5an** [isopropylcyanide/Jwt-Spring-Security-JPA#9]
When deployed as war on server, if token expired instead of sending 406 response code exception, it is sending 500 internal server error exception but if running as a jar it's working fine

**Comment by isopropylcyanide** [comment]
Hi im5an, thank you for reporting the issue. Can you help me with the following:

- Share the stack trace / response payloads in both environments (jar and war)
- Describe the steps you took for me to be able to reproduce the issue
- Your best guess as to why the above scenarios is happening.

Regards,
Aman Garg

**Comment by im5an** [comment]
Fixed issue
` protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response,
                                    FilterChain filterChain) throws ServletException, IOException {
        try {
            String jwt = getJwtFromRequest(request);

            if (StringUtils.hasText(jwt) && jwtTokenProvider.validateToken(jwt)) {
                Long userId = jwtTokenProvider.getUserIdFromJWT(jwt);

                UserDetails userDetails = customUserDetailsService.loadUserById(userId);
                UsernamePasswordAuthenticationToken authentication =
                        new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
                authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                SecurityContextHolder.getContext().setAuthentication(authentication);
            }
        }
        catch (InvalidTokenRequestException ex) {
            logger.error("Invalid JWT signature");
            ResponseWrapper responseWrapper = new ResponseWrapper(false, ex.getMessage(), HttpStatus.NOT_ACCEPTABLE.value());
            response.setStatus(HttpStatus.NOT_ACCEPTABLE.value());
            response.getWriter().write(Util.convertObjectToJson(responseWrapper));
            return;
        } catch (Exception ex) {
            logger.error("Failed to set user authentication in security context: ", ex);
            throw ex;
        }

        filterChain.doFilter(request, response);
    }`

**Comment by isopropylcyanide** [comment]
I do not understand what the issue was as there are no comments. Can you kindly raise a PR for the same?
